name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04  # 🔧 Đổi từ ubuntu-20.04 sang ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"